### PR TITLE
FDSN and FDSN nrt Point to newer diagrams for these services

### PR DESCRIPTION
**Pull request by sue-h-gns**
Using the docs versions as it makes just one source of truth
Next step is to update the one source to contain NRT over EFS

### CODE REVIEW

**Comment by junghao** [comment]
NRT is not using RDS anymore, so we should remove NRT part from the FDSN diagram.

**Review by junghao — CHANGES_REQUESTED** [review]
NRT is not using RDS anymore, so we should remove NRT part from the FDSN diagram.

**Comment by sue-h-gns** [comment]
@junghao  that's a separate repo and a separate PR

**Review by junghao — APPROVED** [review]
OK

**Pull request merged**
